using AccOsuMemory.Core.OsuDataReader.Enum;

namespace AccOsuMemory.Core.OsuDataReader;

public record Beatmap(
    string? ArtistAscii,
    string? ArtistUnicode,
    string? TitleAscii,
    string? TitleUnicode,
    string? Creator,
    string? DifficultyName,
    string? Audio,
    string? Hash,
    string? FileName,
    RankedStatus Status,
    short HitCircleCount,
    short SliderCount,
    short SpinnerCount,
    DateTime LastModified,
    float ApproachRate,
    float CircleSize,
    float HpDrain,
    float OverallDifficulty,
    double SliderVelocity,
    List<double> StdRatings,
    List<double> TaikoRatings,
    List<double> CtbRatings,
    List<double> ManiaRatings,
    int DrainTime,
    int TotalTime,
    int PreviewTime,
    List<TimingPoint> TimingPoints,
    int BeatmapId,
    int BeatmapSetId,
    int ThreadId,
    Grade StdGrade,
    Grade TaikoGrade,
    Grade CtbGrade,
    Grade ManiaGrade,
    short LocalBeatMapOffset,
    float StackLeniency,
    Mode Mode,
    string? SongSource,
    string? Tags,
    short OnlineOffset,
    string? TitleFont,
    bool UnPlayed,
    DateTime LastPlayed,
    bool IsOsz2,
    string? FolderName,
    DateTime LastOnlineCheck,
    bool IsIgnoreSounds,
    bool IsIgnoreSkin,
    bool IsDisableStoryBoard,
    bool IsDisableVideo,
    bool IsVisualOverride,
    int MysteriousLastModified,
    int ManiaScrollSpeed
);

public record TimingPoint(
    double Bpm,
    double Offset,
    bool Inherit
);